apiVersion: v1
kind: Pod
metadata:
  name: "oradb"
labels:
  name: "oradb"
spec:
containers:
  - image: "oracleinanutshell/oracle-xe-11g:latest"
name: "oradb"
ports:
  - containerPort: 1521
restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
name: "oradb"
labels:
  app: "oradb"
spec:
ports:
  - port: 1521
selector:
app: "oradb"


---
apiVersion: v1
kind: ReplicationController
metadata:
  name: "oradb"
labels:
  app: "oradb"
spec:
  replicas: 2
  selector:
  app: "oradb"
template:
  metadata:
  labels:
  app: "oradb"
  spec:
containers:
  - image: "oracleinanutshell/oracle-xe-11g:latest"
name: "oradb"